migrate projects to netstandard2.0 and net6.0
rubicon-oss/CoreRhinoMocks pull request #1
Opened 2022-04-12 04:31 UTC by DrNeil

the CoreRhinoMocks port from original RhinoMocks would be useful as a netstandard 2.0 library as it can be used in net 6 projects
This PR changes the target frameworks to netstandard2.0 for the Rhino.Mocks and net6 for the test projects

2022-05-09 06:30 UTC, MichaelKetting commented
Hello @DrNeil, I've just noticed that I didn't have notifications enabled for this project, so sorry for taking this long to get to you.

I also enabled the issue-tracker on the project, it would be much appriciated if you could add a ticket for this, desribing the intent of the feature. Thanks!

2022-05-09 07:05 UTC, DrNeil commented
Thanks @MichaelKetting 
issue raised, let me know if you need anything else.

2022-05-19 11:10 UTC, MichaelKetting requested changes

2022-05-19 11:10 UTC, MichaelKetting commented on Rhino.Mocks/Rhino.Mocks.csproj
> +    <FileVersion>3.6.0.0</FileVersion>
Please revert this. The code is based off Rhino.Mocks v3.6.1, not v3.6.0.

2022-05-19 11:10 UTC, MichaelKetting commented on Rhino.Mocks/Rhino.Mocks.csproj
> +    <TargetFrameworks>net35;netcoreapp3.1;net6.0;netstandard2.0</TargetFrameworks>
please also update the VS version selection to VS 2022 in the solution file. Otherwise, a double click goes to VS 2019 which isn't compatible with .net 6

2022-05-20 22:48 UTC, DrNeil commented on Rhino.Mocks/Rhino.Mocks.csproj
> +    <FileVersion>3.6.0.0</FileVersion>
done

2022-05-20 22:49 UTC, DrNeil commented on Rhino.Mocks/Rhino.Mocks.csproj
> +    <TargetFrameworks>net35;netcoreapp3.1;net6.0;netstandard2.0</TargetFrameworks>
removed version from sln file - this will now use latest VS installed on PC

2022-05-21 13:36 UTC, MichaelKetting approved these changes

2022-05-22 08:29 UTC, MichaelKetting commented
@DrNeil as you're probably noticed by now, the github workflows need some attention, too:
* .github\workflows\ci_build.yml 
  -> please add tests for net6 (and if possible, netstandard2), matching the established pattern
* .github\workflows\release_build.yml -> please add tests for net6 (and if possible, netstandard2), matching the established pattern
  -> please add invocations for ILRepack for the new targets, matching the established pattern

I also need to patch the workflows since https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ was apparently changed since the last time we ran things on Github.

2022-05-22 09:11 UTC, MichaelKetting commented
- [ ] @DrNeil please don't forget to clean up the redundant commits. I try to keep rolled-back changes out of the history.

2022-05-22 10:02 UTC, MichaelKetting commented
@DrNeil you can now do a rebase of the branch and use the updated workflow. You'll have to update the OS to windows-2022 to support the MSBuild 2022.

2022-06-14 10:03 UTC, MichaelKetting requested changes
@DrNeil I've just received the latest update to your PR and there's now 60 commits in there that also appear to be unrelated to the current branch. I'm not sure what's going on. Could you please check your commit history?

2022-06-15 02:59 UTC, DrNeil commented
Superseded by Update projects to multi-target netstandard and net6 #5

2022-06-15 02:59 UTC, closed without merging

2022-06-15 03:00 UTC, DrNeil commented
@MichaelKetting  yes something went wrong with the merge from develop into this branch - so closed this and created a new PR with the project file changes only